apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: naftiko-shipyard
  name: maritime-registry-api
  description: Mock API for shipyard maritime registry
  tags:
    - maritime
    - registry
    - mock
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: https://raw.githubusercontent.com/jeremnaf/naf-template/main/src/resources/mocks/registry/registry-mock-api.yml
