openapi: 3.0.3
info:
  title: Naftiko Shipyard Maritime Registry API
  version: 1.0.0-alpha1

servers:
  - url: https://mocks.naftiko.net/rest/naftiko-shipyard-maritime-registry-api/1.0.0-alpha1

paths:
  /ships:
    get:
      summary: List ships
      description: Returns a list of registered vessels
      operationId: listShips
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ship'

components:
  schemas:
    Ship:
      type: object
      required:
        - imo_number
        - vessel_name
        - vessel_type
        - flag_code
        - operational_status
      properties:
        imo_number:
          type: string
          example: IMO-9321483
        vessel_name:
          type: string
          example: Northern Star
        vessel_type:
          type: string
          example: cargo
        flag_code:
          type: string
          example: NO
          description: ISO country code of the vessel flag
        operational_status:
          type: string
          example: active
